[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Noam Genish" }]
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
    "pygame-emojis>=0.1.1",
    "pygame-menu>=4.5.2",
    "shared",
]

[project.gui-scripts]
client = "client:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
shared = { workspace = true }
