[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Amit Genish", email = "amitgk159753@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["pygame>=2.6.1", "shared"]

[project.gui-scripts]
client = "client:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
shared = { workspace = true }
