[project]
name = "shared"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Noam Genish" }]
requires-python = ">=3.12"
dependencies = [
    "coloredlogs>=15.0.1",
    'colorama >=0.4.6; platform_system == "Windows"',
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
