[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Noam Genish" }]
requires-python = ">=3.12"
dependencies = ["shared"]

[project.scripts]
server = "server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
shared = { workspace = true }
